# Docs:
#  - https://docs.github.com/en/actions/guides/about-service-containers
#  - https://github.com/actions/example-services/blob/main/.github/workflows/mongodb-service.yml
name: CI
on:
  push:
    branches:
      - master
  pull_request:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PYTHONPATH: "src"
jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.9"
          - "3.10"
        django:
          - "Django>=3.0,<3.2"
          - "Django>=3.2,<3.3"
          - "Django>=4.0,<4.1"
    env:
      DJANGO: ${{ matrix.django }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Set up env
        run: |
          pip install -q pytest pytest-django pycryptodomex "${{ matrix.django }}"
      - name: Run tests
        run: |
          python -m pytest src/django_fields/tests
  Release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Build artifacts
        run: |
          python setup.py sdist bdist_wheel
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          draft: true
